name: golang-pipeline
on: push
jobs:
    test:
        runs-on: ubunutu-latest
        container: golang 1.22
        steps:
            - uses: action/checkout@v4
            
            - name: Run Unit Tests
              run: GOOS=linux GOARCH=amd64 go test
            
            - name: Vet
              run: |
                go vet ./...

